# frozen_string_literal: true

source "https://rubygems.org"

gem 'jwt'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sqlite3'

group :development do
  gem 'irb'
end

# Appended by sue445/isucon-snippets
git_source(:github) { |repo_name| "git@github.com:#{repo_name}" }

# profiling and monitoring
gem "ddtrace", ">= 1.0.0"
gem "sentry-ruby"
gem "datadog_thread_tracer"

# FIXME: ruby 3.2.0-devでインストールできないのでコメントアウト
# https://rubygems.org/gems/google-protobuf/versions/3.21.1-x86-linux
# gem "dogstatsd-ruby"
# gem "google-protobuf", "~> 3.0"

gem "oj"
gem "parallel"
gem "mysql2-nested_hash_bind"

group :development do
  gem "rubocop-isucon", github: "sue445/rubocop-isucon", require: false, branch: "main"
  gem "rubocop_auto_corrector", require: false
end

# 必要に応じて使う
gem "connection_pool"
# gem "puma_worker_killer", require: false
gem "redis"
gem "sidekiq"
gem "sidekiq-cron"
